baseURL = "/"
languageCode = 'en-us'
title = 'paradoxes, anecdotes, and sometimes useful'
theme = 'maverick'

[services]
  [services.googleAnalytics]
    id = 'G-F3KE8ZK4FF'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "A minimal hugo theme focus on content"
  author = 'Calvin Tran'
  items = 10

[params.comments]
  enabled = true
  githubRepo = 'tmackenzie/impact'
  theme = 'github-light'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    pageRef = "/posts/"
    weight = -200
  [[menu.main]]
    identifier = "adrs"
    name = "ADRs"
    pageRef = "/adrs/"
    weight = -100

[markup]
  [markup.goldmark.renderer]
    unsafe = true
[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ''
  hl_inline = false
  lineAnchors = ''
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  noHl = false
  style = 'monokailight'
  tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]